name: Unit testing

on: [ push, pull_request ]

env:
  JSONC_TAG: json-c-0.15-20200726

jobs:
  unit_testing:
    name: Unit testing with ucode
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Build json-c library
        run: |
          git clone https://github.com/json-c/json-c && cd json-c
          git reset --hard $JSONC_TAG
          mkdir build && \
          cmake -S $(pwd) -B $(pwd)/build -DCMAKE_INSTALL_PREFIX=/usr
          make -j$(($(nproc)+1)) -C $(pwd)/build all
          sudo make -C $(pwd)/build install

      - name: Install Lua 5.1
        run: sudo apt-get install lua5.1 liblua5.1-0-dev

      - name: Build OpenWrt libraries
        run: |
          wget https://gitlab.com/ynezz/openwrt-ci/-/raw/master/docker/files/build.sh
          sudo bash ./build.sh

      - name: Build ucode
        run: |
          git clone https://github.com/jow-/ucode && cd ucode
          mkdir build
          sed -i 's;OUTPUT_NAME lib/;OUTPUT_NAME ;g' CMakeLists.txt
          cmake -S $(pwd) -B $(pwd)/build -DCMAKE_INSTALL_PREFIX=/usr
          make -j$(($(nproc)+1)) -C $(pwd)/build all
          sudo make -C $(pwd)/build install

      - name: Run ucode based tests
        run: ./run_tests.sh
